require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'config/puma.rb'
    - 'db/schema.rb'
    - 'config/initializers/devise.rb'
    - 'db/migrate/20230206142737_create_active_storage_tables.active_storage.rb'
    - 'config/environments/production.rb'
    - 'app/controllers/application_controller.rb'
    - 'bin/**/*'


Lint/MissingSuper:
  Enabled: false


# Style -----------------------------------------------------------------------

Style/Documentation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

# Layout ----------------------------------------------------------------------

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
  ExpectedOrder:
      - module_inclusion
      - constants
      - public_class_methods
      - initializer
      - public_methods
      - protected_methods
      - private_methods
